# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: UR5
  joint_model_group_pose: straight
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - seg_1_joint_1
    - seg_1_joint_2
    - seg_2_joint_1
    - seg_2_joint_2
    - seg_3_joint_1
    - seg_3_joint_2
    - seg_4_joint_1
    - seg_4_joint_2
    - seg_5_joint_1
    - seg_5_joint_2
    - seg_6_joint_1
    - seg_6_joint_2
    - seg_7_joint_1
    - seg_7_joint_2
    - seg_8_joint_1
    - seg_8_joint_2
    - seg_9_joint_1
    - seg_9_joint_2
    - seg_10_joint_1
    - seg_10_joint_2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []