<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="needle_segment" params="pre_name name radius length joint_limit">
    <joint name="${name}_fixed" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 ${length}"/>
      <parent link="${pre_name}"/>
      <child link="${name}_fake_1"/>
    </joint>
    <link name="${name}_fake_1"/>
    <joint name="${name}_joint_1" type="revolute">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${name}_fake_1"/>
      <child link="${name}_fake_2"/>
      <axis xyz="1 0 0"/>
      <limit upper="${joint_limit}" lower="${-joint_limit}" effort="1" velocity="1"/>
    </joint>
    <link name="${name}_fake_2"/>
     <joint name="${name}_joint_2" type="revolute">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="${name}_fake_2"/>
      <child link="${name}"/>
      <axis xyz="0 1 0"/>
      <limit upper="${joint_limit}" lower="${-joint_limit}" effort="1" velocity="1"/>
     </joint>
     <link name="${name}">
       <visual>
	 <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
	 <geometry>
	   <cylinder radius="${radius}" length="${length}"/>
	 </geometry>
	 <material name="whilte">
	   <color rgba="1 1 1 1"/>
	 </material>
       </visual>
       <collision>
	 <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
	 <geometry>
	   <cylinder radius="${radius}" length="${length}"/>
	 </geometry>
       </collision>
     </link>
  </xacro:macro>

  <xacro:macro name="needle_seg_loop" params="pre_name name radius length joint_limit qty">
   <xacro:needle_segment pre_name="${pre_name}_${qty-1}" name="${pre_name}_${qty}" radius="${radius}" length="${length}" joint_limit="${joint_limit}"/>
   <xacro:if value="${qty-1}">
     <xacro:needle_seg_loop pre_name="${pre_name}" name="${name}" radius="${radius}" length="${length}" joint_limit="${joint_limit}"  qty="${qty-1}"/>
   </xacro:if>
  </xacro:macro>

  <xacro:macro name="needle_constructor" params="aprx_crv ndl_len ndl_dia n_seg parent=world">
    <xacro:if value="${parent=='world'}">
      <link name="${parent}"/>
    </xacro:if>
    <joint name="${parent}_fixed_joint" type="fixed">
      <origin rpy = "0 0 0" xyz="0 0 ${-ndl_len/n_seg}"/>
      <parent link="${parent}"/>
      <child link="seg_0"/>
    </joint>
    <link name="seg_0"/>
    <xacro:needle_seg_loop pre_name="seg" name="seg" radius="${ndl_dia/2}" length="${ndl_len/n_seg}" joint_limit="${aprx_crv*ndl_len/n_seg/2}" qty="${n_seg}"/>
    <joint name="needle_tip_joint" type="fixed">
      <origin xyz="0 0 ${ndl_len/n_seg}" rpy="0 0 0"/>
      <parent link="seg_${n_seg}"/>
      <child link="needle_tip"/>
    </joint>
    <link name="needle_tip"/>
  </xacro:macro>

</robot>
